language: ruby
rvm:
  - 2.0
  - 2.1.5
  - 2.2
  - 2.3.0
gemfile:
  - Gemfile
  - Gemfile.rails40
  - Gemfile.rails41
matrix:
  include:
    - rvm: 2.3.0
      gemfile: Gemfile.rails50

script: xvfb-run rspec
before_install: gem install bundler -v 1.11.2
